# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Trusted Programming
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
    Huawei opensource work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: trusted-programming
plantuml: "http://www.plantuml.com/plantuml/proxy?cache=no&src=https://raw.githubusercontent.com/trusted-programming/trusted-programming.github.io/plantuml"
exclude:
  - CNAME
  - README.md
  - "Gemfile*"
  - "*.sh"
  - vendor

# Build settings
markdown: kramdown
